name: sampleWorkflow

on:
  workflow_dispatch:

jobs:
  say-hello: 
    runs-on: ubuntu-latest
    steps:
      - name: priting message
        run: echo "Hello World"
  say-bye: 
    runs-on: ubuntu-latest
    steps:
      - name: priting message
        run: echo "bye World"
