name: sampleWorkflow

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  say-hello: 
    runs-on: ubuntu-latest
    steps:
      - name: priting message
        run: echo "Hello World"
      - name: checkout
        uses: actions/checkout@v3
      - run: echo "$( cat hello_world.txt)"
